<a href="https://colab.research.google.com/github/Emmanuelmitra/Python-class-code-/blob/main/class_10_12_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x='Emmanuel'

In [ ]:
print(x)

Emmanuel


In [ ]:
type(x)

str

In [ ]:
len(x)

8

In [ ]:
#indexing the strings 
# syntax=[start:stop:step]
#accessing values inside the string

In [ ]:
x

'Emmanuel'

In [ ]:
x[-1]

'l'

In [ ]:
a='Gautam'

In [ ]:
a[0]

'G'

In [ ]:
a[1]

'a'

In [ ]:
a[5]

'm'

In [ ]:
a[-1]

'm'

In [ ]:
s='360 digit mg is one of the best coaching ceter for machine learning'

In [ ]:
print(s)

360 digit mg is one of the best coaching ceter for machine learning


In [ ]:
s[-2]

'n'

In [ ]:
n='emmanuel'

In [ ]:
n[-2]

'e'

In [ ]:
n[-3]

'u'

In [ ]:
print(s)

Emmanuel mitra


In [ ]:
s1='Emmanuel'
s2=' Mitra'

In [ ]:
w=s1+s2

In [ ]:
w

'Emmanuel Mitra'

In [ ]:
a,b,c=1,2,3

In [ ]:
print(a)

1


In [ ]:
b

2

In [ ]:
c

3

In [ ]:
a=b=c=100

In [ ]:
a

100

In [ ]:
b

100

In [ ]:
c

100

In [ ]:
g,h=20,30

In [ ]:
g

20

In [ ]:
h

30

In [ ]:
x=y=z=200

In [ ]:
x

200

In [ ]:
y

200

In [ ]:
z

200

In [ ]:
a=1
b=2

In [ ]:
a,b=b,a

In [ ]:
a

2

In [ ]:
b

1

In [ ]:
x,y=1,300
x,y=y,x

In [ ]:
x

300

In [ ]:
y

1

In [ ]:
x-y

299

In [ ]:
x

300

In [ ]:
y

1

In [ ]:
x,y=y-1,x

In [ ]:
x=3
x+=4

In [ ]:
x

7

In [ ]:
x=0
x+=3
x

3

In [ ]:
x='360digitmg'

In [ ]:
#what are the rule for assigning the variables 
# 1. should not start with numbers or specialchar except "-"
# 2. cannot use space 
# 3. prefer using small letters 
# 4. avoid using words that have special meaning in pytohn like ,list, print, def,lambda

In [ ]:
a="india"

In [ ]:
a.upper()

'INDIA'

In [ ]:
a.lower()

'india'

In [ ]:
a.capitalize()

'India'

In [ ]:
a='India is country with @ multiple religions @ therefore it is @ secular'

In [ ]:
x=a.split('@')
print(x)

['India is country with ', ' multiple religions ', ' therefore it is ', ' secular']


In [ ]:
states= 'karnataka & maha & kerlna & UP & MP'

In [ ]:
states.split('&')

['karnataka ', ' maha ', ' kerlna ', ' UP ', ' MP']

List

In [ ]:
# features of list 
# 1. Orderd(indexing)
# 2. Mutable 
# 3. []
# 4. holds many type of data 
# 5. duplication is allowed 

In [ ]:
l=[1,2,3,4,5]

In [ ]:
type(l)

list

In [ ]:
l1=[1,2,'emmanuel','India',2+3j, True, 2.6]

In [ ]:
type(l1)

list

In [ ]:
l1[2]

'emmanuel'

In [ ]:
l1[3]

'India'

In [ ]:
l1

[1, 2, 'emmanuel', 'India', (2+3j), True, 2.6]

In [ ]:
l1[2:4]

['emmanuel', 'India']

In [ ]:
l1[-1]

2.6

In [ ]:
#operations on list 

In [ ]:
l=[1,2,3,4,5]

In [ ]:
l.append(299999)

In [ ]:
print(l)

[1, 2, 3, 4, 5, 299999]


In [ ]:
l.append('karnataka')

In [ ]:
l

[1, 2, 3, 4, 5, 299999, 'karnataka']

In [ ]:
l1=[1,2,3,4]
l2=['emmanuel','superhero','ironman','spyderman']

In [ ]:
l1.append(l2)

In [ ]:
print(l1)

[1, 2, 3, 4, ['emmanuel', 'superhero', 'ironman', 'spyderman']]


In [ ]:
l1[4]

['emmanuel', 'superhero', 'ironman', 'spyderman']

In [ ]:
l1=[1,2,3,4]
l2=['emmanuel','superhero','ironman','spyderman']

In [ ]:
l1.extend(l2)

In [ ]:
print(l1)

[1, 2, 3, 4, 'emmanuel', 'superhero', 'ironman', 'spyderman']


In [ ]:
l1[4]

'emmanuel'

In [ ]:
e=[1,3,2,5,6]

In [ ]:
e.insert(1,'emanuel')

In [ ]:
print(e)

[1, 'emanuel', 3, 2, 5, 6]


In [ ]:
e.insert(0,'India')

In [ ]:
print(e)

['India', 1, 'emanuel', 3, 2, 5, 6]


In [ ]:
e.insert(11,'Mitra')

In [ ]:
print(e)

['India', 1, 'emanuel', 3, 2, 5, 'hi', 'hi', '360digitmg', 6, '360digitmg', 'Mitra']


In [ ]:
l=[1,2,3,4,5,'name']

In [ ]:
l.remove('name')

In [ ]:
print(l)

[1, 2, 3, 4, 5]


In [ ]:
l.remove(1)

In [ ]:
print(l)

[2, 3, 4, 5]


In [ ]:
l=['Guj','Tel','Kar','mah','madh']

In [ ]:
l.pop()

'madh'

In [ ]:
l.pop(0)

'Guj'

In [ ]:
l=['Guj','Tel','Kar','mah','madh']

In [ ]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
l=[2,3,1,4,5,7]

In [ ]:
l.sort()

In [ ]:
print(l)

[1, 2, 3, 4, 5, 7]


In [ ]:
l=['emmanuel','superman',' ironman']

In [ ]:
l.reverse()

In [ ]:
print(l)

[' ironman', 'superman', 'emmanuel']


In [ ]:
x=l.copy()

In [ ]:
print(x)

[' ironman', 'superman', 'emmanuel']


In [ ]:
print(l)

[' ironman', 'superman', 'emmanuel']


In [ ]:
l=[1,2,2,2,2,2,5,5,]
l.count(2)

5

In [ ]:
# from typing import OrderedDict
#  features Tuples
# 1. Ordered
# 2. immutable 
# 3. ()
# 4. cannot be changed
# 5. it can hold many types of data
#6. duplication in allowed 

In [ ]:
t=('emmanuel','superman','thanos','blackwidow','doctor')

In [ ]:
l

[1, 2, 'emmanuel', 2, 2, 2, 5, 5]

In [ ]:
l[2]='emmanuel'

In [ ]:
l

[1, 2, 'emmanuel', 2, 2, 2, 5, 5]

In [ ]:
t

('emmanuel', 'superman', 'thanos', 'blackwidow', 'doctor')

In [ ]:
r=(1,1,1,3,4,5)

In [ ]:
type(r)

tuple

In [ ]:
#dictionary
#{}
#{keys: values}
#mutable



In [ ]:
d={1:'emmanuel',2:'mitra'}

In [ ]:
print(d)

{1: 'emmanuel', 2: 'mitra'}


In [ ]:
d.items()

dict_items([(1, 'emmanuel'), (2, 'mitra')])

In [ ]:
d.keys()

dict_keys([1, 2])

In [ ]:
d.values()

dict_values(['emmanuel', 'mitra'])

In [ ]:
game()

new number: 3
number is too small
new number: 5
number is too small
new number: 100
number is too large
new number: 95
congradulations YOU WON


In [ ]:
d1={'names':'azar', 'age': 22, 'coursename':'DS'}

In [ ]:
print(d1)

{'names': 'azar', 'age': 22, 'coursename': 'DS'}


In [ ]:
d1.keys()

dict_keys(['names', 'age', 'coursename'])

In [ ]:
d1.values()

dict_values(['azar', 22, 'DS'])

In [ ]:
d1.items()

dict_items([('names', 'azar'), ('age', 22), ('coursename', 'DS')])

In [ ]:
d1

{'age': 22, 'coursename': 'DS', 'names': 'azar'}

In [ ]:
d1['names']='manoj'

In [ ]:
print(d1)

{'names': 'manoj', 'age': 22, 'coursename': 'DS'}


In [ ]:
d1['age']=30

In [ ]:
d1

{'age': 30, 'coursename': 'DS', 'names': 'manoj'}

In [ ]:
d2={'name': ['superman','ironman'], 'planet':['earth','jupyter'],'age': ['50','40']}

In [ ]:
print(type(d2))

<class 'dict'>


In [ ]:
d2.items()

dict_items([('name', ['superman', 'ironman']), ('planet', ['earth', 'jupyter']), ('age', ['50', '40'])])

In [ ]:
d2.keys()

dict_keys(['name', 'planet', 'age'])

In [ ]:
d2.values()

dict_values(['superman', 'earth', '50'])

In [ ]:
d2['name']

['superman', 'ironman']

In [ ]:
d2['age']

['50', '40']

In [ ]:
d2['planet']

['earth', 'jupyter']

In [ ]:
d2['name'][1]

'ironman'

In [ ]:
d2['name'][0][0]

's'

## Sets

In [ ]:
#Unordered 
#Indexing is not possible 
#contains unique elements 
#duplication is not allowed 
#{} 


In [ ]:
s={1,2,3,4,5}

In [ ]:
type(s)

set

In [ ]:
s1={1,2,1,1,1,3,4,2,6,7}

In [ ]:
print(s1)

{1, 2, 3, 4, 6, 7}


In [ ]:
s2={'emmanuel','Mitra','superman','spyderman'}

In [ ]:
print(s2)

{'emmanuel', 'Mitra', 'superman', 'spyderman'}


In [ ]:
print(s1)

{1, 2, 3, 4, 6, 7}


In [ ]:
s3=s1.intersection(s2)

In [ ]:
print(s3)

set()


In [ ]:
s1={1,2,3,4,5}
s2={1,8,9,0,2}

In [ ]:
s1.intersection(s2)

{1, 2}

In [ ]:
s1={1,2}

In [ ]:
s1={1,2,3,9,10}
s2={4,5,2,1,3,10}

In [ ]:
s1.union(s2)

{1, 2, 3, 4, 5, 9, 10}

In [ ]:
s1={1,2,3}

# Operators

In [ ]:
#Arithmatic operators 
# +,-*%

In [ ]:
a=10
b=1
a+b

11

In [ ]:
a-b

9

In [ ]:
a*b

10

In [ ]:
x=4
y=2
x/y

2.0

In [ ]:
#floordivision
x//2

2

In [ ]:
a=4
b=2
a**2

16

# Comparision operators

In [ ]:
a=1
b=2


In [ ]:
a==b

False

In [ ]:
a>b

False

In [ ]:
a<b

True

In [ ]:
a>=b

False

In [ ]:
a<=b

True

In [ ]:
a!=b

True

# Assignment operators

In [ ]:
a=1
b=2

In [ ]:
c=a+b

In [ ]:
c

3

In [ ]:
c+=b

In [ ]:
c

5

In [ ]:
c=3
b=4

In [ ]:
c+=b

In [ ]:
c

7

In [ ]:
a=3
b=8
a-=b

In [ ]:
print(a)

-5


In [ ]:
a*=b

In [ ]:
a

-40

In [ ]:
a=3
b=4
a*=b

In [ ]:
a

12

# Membership operators 

In [ ]:
'e' in 'Emmanuel'

True

In [ ]:
'm' in 'emmanuel'

True

In [ ]:
'E' in 'emmanuel'

False

In [ ]:
'p' not in 'python'

False

In [ ]:
'y' not in 'pYthon'

True

In [ ]:
a=1

In [ ]:
a is 1

True

In [ ]:
A=1
1 is A

True

In [ ]:
a=2
2 is a

True

In [ ]:
a=1
a is not 1

False

# String Formating 

In [ ]:
a='this is python class'

In [ ]:
type(a)

str

In [ ]:
'%s my name is  and age is %d '%('spyderman',88)

'spyderman my name is  and age is 88 '

In [ ]:
#how to take input from user?
name=input('enter your name')


enter your nameemmanuel


In [ ]:
age=int(input('enter your age: '))

enter your age: 22


In [ ]:
type(age)

int

In [ ]:
name=input('enter your name: ')
age=int(input('enter your age: '))
print('your name is %s and your age is %d' %(name,age))

enter your name: hero
enter your age: 33
your name is hero and your age is 33


In [ ]:
def xyz():

  name=input('enter your name: ')
  age=int(input('enter your age: '))
  print(' your name is {0} and your age is {1} ' .format(name,age))

In [ ]:
name=input('enter your name: ')
age=int(input('enter your weight: '))
print(f'{name} is {age} kgs')

enter your name: emmauel
enter your weight: 33
emmauel is 33 kgs


# List Comprehension

In [ ]:
l=[1,2,3,4,5]
for i in l:
  print(i)

1
2
3
4
5


In [ ]:
[i for i in l]

[1, 2, 3, 4, 5]

In [ ]:
l=[1,2,3,4,5]


In [ ]:
[i+100 for i in l]

[101, 102, 103, 104, 105]

In [ ]:
n='emmanuel'
[i for i in n]

['e', 'm', 'm', 'a', 'n', 'u', 'e', 'l']

In [ ]:
l=[1,2,3,4,5]
[i for i in l if i%2==0]


[2, 4]

In [ ]:
l2=[i+10 for i in l if i%2==0]
type(l2)

list

In [ ]:
for i in l:
  if i%2==0:
    print(i+10)

12
14


In [ ]:
l=[1,2,3,4,5,6,7,8,9,10]

['largenumber' for i in l if i>=5]



['largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber']

In [ ]:
for i in l:
  if i>5:
    print('large number')
  else:
    print('small number')

small number
small number
small number
small number
small number
large number
large number
large number
large number
large number


In [ ]:
['large' if i>5 else 'small' for i in l ]

['small',
 'small',
 'small',
 'small',
 'small',
 'large',
 'large',
 'large',
 'large',
 'large']

In [ ]:
l=[1,2,3,4,5,5,6,7,8,9]

In [ ]:
[1 if i>=5 else 0 for i in l]

[0, 0, 0, 0, 1, 1, 1, 1, 1, 1]

In [ ]:
l=['male', 'male', 'female','female', 'female']

In [ ]:
[0 if i=='male' else 1 for i in l]

[0, 0, 1, 1, 1]

# While loop 



In [ ]:
i=10

In [ ]:
while i>0:
  print(i)
  i=i-1

10
9
8
7
6
5
4
3
2
1


In [ ]:
#Game

In [ ]:
def game():
  rnum= int(20*5+5-10)
  guess=0

  while guess!=rnum:
    guess=int(input('new number: '))
    if guess>0:
      if guess>rnum:
        print('number is too large')
      elif guess<rnum:
        print('number is too small')
    else:
      print('sorry that you are giveup ')
      break
  else:
    print('congradulations YOU WON')

In [ ]:
game()

new number: 4
number is too small
new number: 5
number is too small
new number: 100
number is too large
new number: 10000
number is too large
new number: 95
congradulations YOU WON


In [ ]:
xyz()

enter your name: emmanuel
enter your age: 26
 your name is emmanuel and your age is 26 


In [ ]:
def who_you_are():
  is_male=True
  is_tall=False
  if is_male and is_tall:
      print("You are Bahubali")
  else:
      print("You are khalipili")


In [ ]:
who_you_are()

You are khalipili


In [ ]:
def vicky():
    name=input('enter your name: ')
    age=int(input('enter your age: '))
    print(f'your name is {name} and your age is {age}.')
    return age


In [ ]:
vicky()

enter your name: e
enter your age: 2
your name is e and your age is 2.


2

In [ ]:
l=[1,2,3,4,5]
def evenid(l):
  for i in l:
    if i%2==0:
      print(i)

In [ ]:
evenid([1,2,1,2,1,2,100,25,24,22,2])

2
2
2
100
24
22
2


In [ ]:
evenid([2,3,4])

2
4


In [ ]:
def eoid(x):
    l = []
    for i in x:
        if i % 2 == 0:
            l.append(i)
    return print(i)
lst = [1,2,3,4,5,6,7,8,9,10]
eoid(lst)
eoid(lst)


10
10


In [ ]:
def eoid(x):
    l = []
    for i in x:
        if i % 2 == 0:
            l.append(i)
    return print(l)
lst = [1,2,3,4,5,6,7,8,9,10]
eoid(lst)


[2, 4, 6, 8, 10]


In [ ]:
f=lambda x: x%2==0

In [ ]:
l=list(map(f,[1,2,3,4,5]))

In [ ]:
print(l)

[False, True, False, True, False]


## lambda function 

In [ ]:
l=[1,2,3,4,5]


In [ ]:
f=lambda x: x**2

In [ ]:
list(map(f,l))

[1, 4, 9, 16, 25]

In [ ]:
l=[1,2,3,4,5]


In [ ]:
f=lambda y: str(y)

In [ ]:
l2=list(map(f,l))

In [ ]:
print(l2)

['1', '2', '3', '4', '5']


In [ ]:
type(l2[1])

str

# **Pandas**

In [ ]:
import pandas as pd

In [ ]:
l1=[1,2,3,4,5]
l2=[122,133,144,155,166]
l3=[200,300,400,500,600]

In [ ]:
df=pd.DataFrame(columns=[777,888,999])

In [ ]:
df

Empty DataFrame
Columns: [777, 888, 999]
Index: []

In [ ]:
df[777]=l1
df[888]=l2
df[999]=l3

In [ ]:
df

777  888  999
0    1  122  200
1    2  133  300
2    3  144  400
3    4  155  500
4    5  166  600

In [ ]:
#how to convert dictionary to dataframe

In [ ]:
d={'name':['emmanuel','ironman','superman','krish'],'age': [22,23,24,25]}

In [ ]:
df=pd.DataFrame({'name':['emmanuel','ironman','superman','krish'],'age': [22,23,24,25]})

In [ ]:
df.head()

name  age
0  emmanuel   22
1   ironman   23
2  superman   24
3     krish   25

In [ ]:
df['marks']=[22,33,44,55]

In [ ]:
df

name  age  marks
0  emmanuel   22     22
1   ironman   23     33
2  superman   24     44
3     krish   25     55

In [ ]:
df['percent']={22,33,44,55}

In [ ]:
df

name  age  marks  percent
0  emmanuel   22     22       33
1   ironman   23     33       44
2  superman   24     44       22
3     krish   25     55       55

In [ ]:
df['age']=[55,66,77,88]

In [ ]:
df

name  age  marks  percent
0  emmanuel   55     22       33
1   ironman   66     33       44
2  superman   77     44       22
3     krish   88     55       55

In [ ]:
l=[1,2,3,4,5,6]

In [ ]:
s=pd.Series(l)

In [ ]:
type(s)
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [ ]:
t=(4,5,6,7,8,9)

In [ ]:
s1=pd.Series(t)

In [ ]:
type(s1)
print(s1)

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int64


In [ ]:
print(s)


0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [ ]:
print(s1)

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int64


In [ ]:
df=pd.DataFrame(columns=['name','phno'])

In [ ]:
df

Empty DataFrame
Columns: [name, phno]
Index: []

In [ ]:
df['name']=s

In [ ]:
df

name phno
0     1  NaN
1     2  NaN
2     3  NaN
3     4  NaN
4     5  NaN
5     6  NaN

In [ ]:
df['phno']=s1

In [ ]:
df

name  phno
0     1     4
1     2     5
2     3     6
3     4     7
4     5     8
5     6     9

In [ ]:
#how to read file from pandas 

In [ ]:
import pandas as pd


In [ ]:
df=pd.read_csv('/content/Crop_recommendation kaggle npk.csv')

In [ ]:
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [ ]:
df[:3]

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice

In [ ]:
df[:]

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [ ]:
df.iloc[:5,:2]

N   P
0  90  42
1  85  58
2  60  55
3  74  35
4  78  42

In [ ]:
df.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')

In [ ]:
df.loc[:,['N', 'P']]

N   P
0      90  42
1      85  58
2      60  55
3      74  35
4      78  42
...   ...  ..
2195  107  34
2196   99  15
2197  118  33
2198  117  32
2199  104  18

[2200 rows x 2 columns]

In [ ]:
df.loc[df['N']]

N   P   K  temperature   humidity        ph    rainfall  label
90   93  53  38    26.929951  81.914112  7.069172  290.679378   rice
85   66  60  38    22.085766  83.470383  6.372576  231.736496   rice
60   72  40  38    20.414470  82.208026  7.592491  245.151130   rice
74   75  54  36    26.294655  84.569193  7.023936  257.491491   rice
78   77  36  37    26.884449  81.460337  6.136132  194.576656   rice
..   ..  ..  ..          ...        ...       ...         ...    ...
107  89  60  19    25.191924  66.690290  5.913665   78.066396  maize
99   65  37  40    23.359054  83.595123  5.333323  188.413665   rice
118  66  53  19    23.093481  60.115938  6.033550   65.497307  maize
117  61  41  17    25.142061  65.261851  6.021902   76.684560  maize
104  61  38  20    18.478913  62.695039  5.970458   65.438354  maize

[2200 rows x 8 columns]

In [ ]:
df=pd.read_csv('/content/Crop_recommendation kaggle npk.csv')
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [ ]:
df.loc[0:10,['N', 'P']]

N   P
0   90  42
1   85  58
2   60  55
3   74  35
4   78  42
5   69  37
6   69  55
7   94  53
8   89  54
9   68  58
10  91  53

In [ ]:
df.loc[0:5,['N',"P"]]

N   P
0  90  42
1  85  58
2  60  55
3  74  35
4  78  42
5  69  37

# groupby function

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/mba.csv')

In [4]:
df.head()

datasrno  workex  gmat
0         1      21   720
1         2     107   640
2         3      57   740
3         4      99   690
4         5     208   710

In [5]:
df.tail()

datasrno  workex  gmat
768       769      88   620
769       770     132   670
770       771      28   610
771       772      10   610
772       773      52   620

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773 entries, 0 to 772
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datasrno  773 non-null    int64
 1   workex    773 non-null    int64
 2   gmat      773 non-null    int64
dtypes: int64(3)
memory usage: 18.2 KB


In [7]:
df.describe()

datasrno     workex        gmat
count  773.00000  773.00000  773.000000
mean   387.00000   57.50194  711.164295
std    223.29017   27.38682   29.339714
min      1.00000    9.00000  600.000000
25%    194.00000   41.00000  690.000000
50%    387.00000   52.00000  710.000000
75%    580.00000   69.00000  730.000000
max    773.00000  279.00000  780.000000

In [8]:
df.head()

datasrno  workex  gmat
0         1      21   720
1         2     107   640
2         3      57   740
3         4      99   690
4         5     208   710

In [10]:
df.gmat.count()

773

In [11]:
df.columns

Index(['datasrno', 'workex', 'gmat'], dtype='object')

In [16]:
df['workex'].count()

773

In [14]:
df.groupby('gmat').count()

datasrno  workex
gmat                  
600          2       2
610          4       4
620          6       6
630          3       3
640          3       3
650         17      17
660         17      17
670         13      13
680         54      54
690         78      78
700         65      65
710        178     178
720        104     104
730         76      76
740         67      67
750         35      35
760         32      32
770         17      17
780          2       2

## **numpy**

In [18]:
import numpy as np

In [19]:
x=[1,2,3,4,5]

In [20]:
x*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [21]:
y=np.array(x)

In [22]:
type(y)

numpy.ndarray

In [24]:
print(y)

[1 2 3 4 5]


In [27]:
y2=y*2
print(y2)

[ 2  4  6  8 10]


In [29]:
y3=y+100
print(y3)

[101 102 103 104 105]


In [30]:
# create 1d array

In [33]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [34]:
type(a)

numpy.ndarray

In [35]:
# creating two dimentional array 

In [37]:
b=np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [39]:
# creating numpy array with help of range function 
# syntax: np.arange(start,end,step)

In [41]:
c=np.arange(1,10,2)
print(c)

[1 3 5 7 9]


In [43]:
d=np.arange(1,20,3)
print(d)

[ 1  4  7 10 13 16 19]


In [44]:
#create numpy array filled with zeros 

In [45]:
np.zeros((1,2))

array([[0., 0.]])

In [46]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
# create numpy array filled with ones

In [49]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [51]:
np.ones((6,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
#create empty array

In [53]:
np.empty((2,2))

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])

In [54]:
#create random array

In [57]:
np.random.random((5,5))

array([[0.57864065, 0.89196188, 0.79627311, 0.73687699, 0.33148226],
       [0.20461939, 0.71074853, 0.41667896, 0.82104801, 0.35084407],
       [0.10152677, 0.28538161, 0.20169404, 0.44611342, 0.34872209],
       [0.39610434, 0.33104688, 0.52043303, 0.60888119, 0.42988768],
       [0.5273081 , 0.13640323, 0.67547198, 0.03783074, 0.67484613]])

In [58]:
#add evenly spaced values between intervalus of array of lenth 

In [61]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [62]:
len(a)

4

In [63]:
print(a)

[1 2 3 4]


In [64]:
len(a)

4

In [65]:
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [66]:
len(b)

2

In [67]:
a.dtype

dtype('int64')

In [68]:
b.dtype

dtype('int64')

## numpy matrix

In [69]:
#how to create a numpy matrix

In [71]:
np.matrix('1 2;3 4')

matrix([[1, 2],
        [3, 4]])

In [74]:
np.matrix('1 2 3 4 5; 6 7 8 9 10; 10 11 12 14 15')

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [10, 11, 12, 14, 15]])

In [75]:
# 2 method numpy matri

In [79]:
b=np.matrix([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [78]:
b.shape

(2, 4)

In [80]:
#create a sequence of integers with specific values 

In [81]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [82]:
# differnce between arange and range

In [90]:
f=np.arange(0,50,5)
print(f)
type(f)

[ 0  5 10 15 20 25 30 35 40 45]


numpy.ndarray

In [94]:
f=np.array(range(0,50,5))
print(f)
type(f)

[ 0  5 10 15 20 25 30 35 40 45]


numpy.ndarray

In [99]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [100]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
np.delete(a,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [106]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [107]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
np.delete(b,2,axis=1)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [109]:
# reshaping the array

In [110]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [111]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
c.shape

(3, 3)

In [118]:
c[2]

array([7, 8, 9])

In [120]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
c[2,1]

8

In [126]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
c=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,100]])

In [131]:
c

array([[  1,   2,   3,   4],
       [  4,   5,   6,   7],
       [  7,   8,   9, 100]])

In [135]:
c3=c.reshape(6,2)
c3

array([[  1,   2],
       [  3,   4],
       [  4,   5],
       [  6,   7],
       [  7,   8],
       [  9, 100]])

In [136]:
c3.flatten()

array([  1,   2,   3,   4,   4,   5,   6,   7,   7,   8,   9, 100])

In [137]:
# end nupy